##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Build indy-cli-App indy docker images triggered by :
#  - push on develop branch for latest tags 
#  - create tag vx.y.z for release tags
#  - Can be triggered manually

name: Build indy-cli App indy Images

on:
  workflow_dispatch:
  create:
    tags:
      - v*
  push:
    branches:
      - develop
    paths:
      - 'examples/indy-cli-app indy/**'
      - '.github/workflows indy_images_build.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ghcr.io/${{ github.repository_owner }}

jobs:
  # on push to develop branch, create docker tags latest
 indy-latest:
    if: ${{ startsWith(github.ref, 'refs/heads/develop') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to the container registry
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push indy-cli app latest
      id: indy-cli_latest
      uses: docker/build-push-action@v2
      with:
        context: examples/indy-cli-app indy/express_nodeJS
        push: true
        tags: ${{ env.IMAGE_PATH }}/bevel-indy-cli indy:express-app-latest

 indy-release: 
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to the container registry
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push indy-cli app release
      id: indy_indy-cli_release
      uses: docker/build-push-action@v2
      with:
        context: examples/indy-cli-app indy/express_nodeJS
        push: true
        tags: ${{ env.IMAGE_PATH }}/bevel-indy-cli indy:express-app-${{ steps.vars.outputs.tag }},${{ env.IMAGE_PATH }}/bevel-indy-cli indy:express-app-stable